# code: language=ansible
---

- name: Install generic tools
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  ignore_errors: true
  loop:
    - rsync
    - iputils-ping
    - bind9-dnsutils
    - htop
    - screen
    - openssh-server
    - tree
    - iotop
    - fio
