# code: language=ansible
---

- name: Install zsh | ohmyzsh
  ansible.builtin.import_role:
    name: diodonfrost.ohmyzsh
  become: true
  vars:
    ohmyzsh_theme: powerlevel10k/powerlevel10k
    ohmyzsh_users: "{{ zshell_users }}"
    ohmyzsh_plugins: "{{ zshell_plugins }}"

- name: Install Plugins
  ansible.builtin.include_tasks: git-plugin.yml
  loop: "{{ zshell_external_plugins }}"
  loop_control:
    loop_var: plugin_items

- name: Install packages
  ansible.builtin.package:
    name: "{{ zshell_required_packages }}"
    state: present

- name: Install z.lua
  ansible.builtin.import_tasks: z.lua.yml

- name: Install p10k
  ansible.builtin.import_role:
    name: diodonfrost.p10k
  vars:
    p10k_users: "{{ zshell_users }}"
    zsh_plugin: ohmyzsh
    p10k_prompt_style: rainbow

- name: Override p10k.zsh with custom
  ansible.builtin.copy:
    src: "{{ zshell_p10k_config_path | default('p10k.zsh', true) }}"
    dest: "{{ item['home'] }}/.p10k.zsh"
    owner: "{{ item['name'] }}"
    group: "{{ item['group'] }}"
    mode: '0644'
  loop: "{{ p10k_users_information }}"
