# code: language=ansible
---

- name: Install lua
  become: true
  ansible.builtin.package:
    name: lua5.2
    state: present

- name: Install z.lua
  ansible.builtin.git:
    repo: https://github.com/skywind3000/z.lua.git
    dest: "{{ item['home'] }}/.z.lua"
    update: false
  loop: "{{ ohmyzsh_users_information }}"

- name: Configure z.lua
  ansible.builtin.blockinfile:
    path: "{{ item['home'] }}/.zshrc"
    block: |
      # z.lua for zsh init
      eval "$(lua ~/.z.lua/z.lua  --init zsh once enhanced)"
    marker: "# {mark} roles/curtis.zshell ANSIBLE MANAGED BLOCK"
  loop: "{{ ohmyzsh_users_information }}"
