# code: language=ansible
---
zshell_users:
  - "{{ ansible_user_id }}"

zshell_plugins:
  - git
  - command-not-found
  - colored-man-pages
  - vi-mode
  - zsh-autosuggestions
  - zsh-syntax-highlighting

zshell_external_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
