---
- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ zsh_bin_path }}"
  become: true
  loop: "{{ p10k_users }}"

- name: Setup powerlevel10k
  ansible.builtin.template:
    src: "p10k-{{ p10k_style[p10k_prompt_style] }}.zsh.j2"
    dest: "{{ item['home'] }}/.p10k.zsh"
    owner: "{{ item['name'] }}"
    group: "{{ item['group'] }}"
    mode: '0644'
  loop: "{{ p10k_users_information }}"
