# code: language=ansible
---
- name: Deploy
  hosts: all
  roles:
    - role: chusiang.switch-apt-mirror
      tags:
        - apt-mirror
      vars:
        ubuntu_apt_mirror: mirror.nju.edu.cn
        debian_apt_mirror: mirror.nju.edu.cn

    - role: curtis.zshell
      tags:
        - p10k

    - role: curtis.misc
      tags:
        - zh

    - role: curtis.zh-cn-lang
      tags:
        - zh

    - role: curtis.generic-tools
      tags:
        generic-tools

    - role: curtis.cpp-env
      tags:
        - cpp

    - role: curtis.gui
      tags:
        - gui

    - role: curtis.conda-pdm
      tags:
        - conda-pdm

    # - role: nvm
    #   tags:
    #     - nvm

    # - role: jenv
    #   tags:
    #     - jenv

    # - role: docker
    #   tags:
    #     - docker

    # - role: tensorflow
    #   tags:
    #     - tensorflow

    # - role: pytorch
    #   tags:
    #     - pytorch
